# Generated by Django 3.2.9 on 2021-11-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='assigned_teacher',
        ),
        migrations.AddField(
            model_name='courses',
            name='assigned_teacher',
            field=models.ManyToManyField(null=True, to='academics.Lecturers'),
        ),
    ]
