# Generated by Django 3.2.9 on 2021-11-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_auto_20211108_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='fees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
