# Generated by Django 3.2.9 on 2021-11-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_comments_lecturee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='assigned_teacher',
            field=models.ManyToManyField(to='academics.Lecturers'),
        ),
    ]
